# --- !Ups

CREATE TABLE IF NOT EXISTS CONFIG(
  wait_period INT
);

CREATE TABLE IF NOT EXISTS SCRIPT(
  path VARCHAR(1023)
);

CREATE TABLE IF NOT EXISTS ACCOUNT(
  screen_name VARCHAR(20),
  access_token VARCHAR(100),
  access_token_secret VARCHAR(200)
);

# --- !Downs

DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS SCRIPT;
DROP TABLE IF EXISTS ACCOUNT;
