# --- !Ups

CREATE TABLE IF NOT EXISTS CONFIG(
  PERIOD INT
);

CREATE TABLE IF NOT EXISTS SCRIPT(
  PATH VARCHAR(1023)
);

CREATE TABLE IF NOT EXISTS ACCOUNT(
  SCREEN_NAME VARCHAR(20),
  ACCESS_TOKEN VARCHAR(100),
  ACCESS_TOKEN_SECRET VARCHAR(200)
);

# --- !Downs

DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS SCRIPT;
DROP TABLE IF EXISTS ACCOUNT;
